//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Device = new HashSet<Device>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Description { get; set; }
        public int ClientId { get; set; }
        public int OrderStatusId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> FeedbackId { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Device { get; set; }
        public virtual Feedback Feedback { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
